### ISSUE TITLE
Create REST API for ResponseConstraint resource

### ISSUE THREAD

**Issue by tylerthome** [hackforla/shared-housing#150]
### Overview
Create a REST API handling add, update, retrieval and delete operations on the response constraint resource.

#### Add HTTP stubs to server source code

* Retrieve all constraints by location ID
  * method: GET
  * route: /api/locations/{locationId}/constraints
  * accepts: Location ID (integer or uuid)
  * returns: JSON array of ResponseConstraint objects (described below)  
* Add constraint
  * method: POST
  * route: /api/locations/{locationId}/constraints
  * accepts: JSON payload containing ResponseConstraint object
  * returns: HTTP response with status 200, 400 or 500 depending on result of operation  
* Update constraint information by ID
  * method: PUT
  * route: /api/locations/{locationId}/constraints/{constraintId}
  * accepts: JSON payload containing ResponseConstraint object
  * returns: HTTP response with status 200, 400 or 500 depending on result of operation  
* (Bonus) Update constraint information attribute by constraint ID
  * method: PATCH
  * route: /api/locations/{locationId}/constraints/{constraintId}
  * accepts: [JSON Patch](http://jsonpatch.com/) payload for a ResponseConstraint object
  * returns: HTTP response with status 200, 400 or 500 depending on result of operation

### Resources/Instructions
* Use or improve upon the following data model for the JSON payload:
```yaml
ResponseConstraint:
    locationId: integer
    questionId: integer
    acceptedValues: Array<string | integer | boolean>
    constraintId?: integer
```

* Make use of Flask's declarative [route definition syntax](https://hackersandslackers.com/the-art-of-building-flask-routes/) to specify URIs

**Comment by kkchu791** [comment]
For the data model
```
ResponseConstraint:
    locationId: integer
    questionId: integer
    acceptedValues: Array<string | integer | boolean>
    constraintId?: integer
```

is the constraintId supposed to have a question mark?

Also, is this what the JSON might look like for one response constraint?

```
response_constraint = {
  id: 1,
  locationId: 1,
  questionId: 1,
  acceptedValue: ["no", "nope", "i don't like pets"],
  constraintId: 1
```

If this was a relational model, i would see it as 

**LocationTable**
{id: 1, location: "LA family housing building"}

**QuestionTable**
{id: 1, question: "Do you like pets?"}

**ConstraintTable**
{id: 1, constraint: "no pets"}

**ResponseConstraint**
{id: 1, locationId: 1, questionId: 1, acceptedValue=["no", "nope", "i don't like pets"], constraintId: 1}

Do I have it correct with the modeling?
